### ISSUE TITLE
Available on npm?

### ISSUE THREAD

**Issue by eddiezane** [go1dfish/nodewhal#1]
Thanks for the great library! Wound up using it at a hackathon this past weekend. Any plans for making it available on npm?

**Comment by go1dfish** [comment]
I'll do this when I can find the time, it would be my first NPM module.

Glad you found it useful; sorry it took me so long to respond.

The EventSource stream nodewhal uses went down a few months ago (took down my bots with it) but I have recreated my own implementation here:

https://github.com/go1dfish/reddit-stream

**Comment by michaelowens** [comment]
I would also love to see this on NPM! Best wrapper out there! But for now you can use `npm install go1dfish/nodewhal --save`

**Comment by ghost** [comment]
Any news @go1dfish  ? come on its not hard ^^
You just gotta follow [those instructions](https://gist.github.com/coolaj86/1318304).
